AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CurrentTemperatureInCovilhaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib
      Handler: index.currentTemperatureInCovilha
      Runtime: nodejs12.x
      Events:
        HappyTempApi:
          Type: Api
          Properties:
            Path: /currenttempincovilha
            Method: GET

  AverageTemperatureInSfaxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib
      Handler: index.averageTemperatureInSfax
      Runtime: nodejs12.x
      Events:
        HappyTempApi:
          Type: Api
          Properties:
            Path: /avgtempinsfax
            Method: GET

Metadata:
  AWS::ServerlessRepo::Application:
    Name: happy-temp
    Description: Assignment regarding Node.js/Typescript/AWS
    Author: Tarty
    SpdxLicenseId: ISC
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['assignments']
    HomePageUrl: https://github.com/Tarty/happy-temp
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/Tarty/happy-temp
